config-version: 2

name: "brightwheel"
version: "0.1.0"
require-dbt-version: ">=1.5.0"

profile: brightwheel

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["data-tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"