version: 2

models:
  - name: base__source1_nv_monthly_extract
    description: Extract of source 1 (NV) leads -- new and updated
  - name: base__source2_ok_monthly_extract
    description: Extract of source 2 (OK) leads -- new and updated
  - name: base__source3_tx_monthly_extract
    description: Extract of source 3 (TX) leads -- new and updated
  - name: base__salesforce_leads
    description: Extract of existing Salesforce leads
    columns:
      - name: id
        tests:
          - not_null
          - unique
      - name: is_deleted
        description: Has the lead been deleted?
        tests:
          - accepted_values:
              values: ['TRUE','FALSE']
      - name: is_converted
        description: Has the lead been converted to a customer?
        tests:
          - accepted_values:
              values: ['TRUE','FALSE']