with final as (
    select 
        null as accepts_financial_aid,
        null as ages_served,
        capacity_c::numeric as capacity,
        null::date as certificate_expiration_date,
        city,
        street as address1,
        null as address2, --TODO
        company,
        phone,
        mobile_phone as phone2,
        null as county,
        null as curriculum_type,
        email,
        first_name,
        null as "language",
        last_name,
        null as license_status,
        null::date as license_issued,
        null::numeric as license_number,
        null::date as license_renewed,
        null as license_type,
        null as licensee_name,
        null::numeric as max_age,
        null::numeric as min_age,
        null as operator,
        null as provider_id,
        null as schedule,
        "state",
        title,
        website,
        postal_code as zip,
        null as facility_type,
        lead_source,
        is_deleted,
        "status" as lead_status,
        is_converted,
        created_date,
        last_modified_date,
        last_activity_date,
        last_viewed_date,
        last_referenced_date,
        email_bounced_reason,
        email_bounced_date,
        outreach_stage_c,
        lead_source_last_updated_c
    from {{ ref('base__salesforce_leads') }}
)
select * from final