version: 2

models:
  - name: core__source1_nv_monthly_extract_cleansed
    description: Extract of source 1 (NV) leads -- cleansed  
  - name: core__source2_ok_monthly_extract_cleansed
    description: Extract of source 2 (OK) leads -- cleansed
  - name: core__source3_tx_monthly_extract_cleansed
    description: Extract of source 3 (TX) leads -- cleansed
  - name: core__combined_leads
    description: Combined leads from this month's extract files (Salesforce excluded)
  - name: core__salesforce_leads_standardized
    description: Salesforce existing leads translated into standardized schema format